recipe: default.v1

language: zh
pipeline:
# components.tokenizer.MicroTokenizer, components.tokenizer.MyBertTokenizer
  - name: components.tokenizer.MicroTokenizer
    dictionary_path: "data/dict"
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: bert-base-chinese
  - name: DIETClassifier
    epoches: 100
    tensorboard_log_directory: ./log
    learning_rate: 0.001
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1
  - name: EntitySynonymMapper
  - name: ResponseSelector

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 10
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"