version: '3.0'

services:
  rasa:
    image: rasa/rasa:3.0.8-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./formbot/:/app/"
    environment:
      MPLCONFIGDIR: "/tmp/"
    command:
    - run
    - --enable-api
    - --cors
    - "*"

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./formbot/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}